### ISSUE TITLE
[Suggestion] Too many commits

### ISSUE THREAD

**Issue by sharkbait2** [JovianSpace/Kitsune#1]
Hi, just here to give you a friendly suggestion that apparently you have a lots of tiny commits for every single tiny changes (You already have 10 commits for 3 lines of readme). Which can then pollute your commit history very soon.

### 1. use [`git commit --amend`](https://www.atlassian.com/git/tutorials/rewriting-history) to override the last commit with the new changes.
ex: after a new change in the source.
```
git add .
git commit --amend -m "A descriptive message."
git push
```

### 2. use [`git rebase -i HEAD~5`](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) to squash the last 5 commits into a single commit.

![rebase](https://user-images.githubusercontent.com/84169674/121613813-fb8bdc00-ca7a-11eb-8220-d71cb885f19c.gif)

Have a great day!

**Comment by karina-jovian** [comment]
Hi, thank you for the advice! The reason why there’s so much commits is that I used only basic github web UI for them. I just have no enough time to update README properly, because I have several projects and the paid job. I’ll try to organize my workflow better soon.

Thank you again and have a nice day too!
